user  nginx;
worker_processes  auto;

load_module /usr/lib/nginx/modules/ngx_stream_module.so;

error_log  /logs/upstream_error error;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

stream {
    include /etc/nginx/deny;
    log_format basic '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received';
    access_log off;

    upstream other {
        server 10.10.0.2:443;
    }

    upstream reality {
        server 10.10.0.9:33443;
    }

    map_hash_bucket_size 128;
    map $ssl_preread_server_name $sni_name {
#domain
okcdn.ru reality;
#domain

        default other;
    }

    server {
        listen          443 reuseport;
        proxy_pass      $sni_name;
        proxy_protocol  on;
        ssl_preread     on;
    }

    server {
        listen          443 udp;
        proxy_pass      $sni_name;
        proxy_protocol  on;
        ssl_preread     on;
    }
}
